# Generated by Django 5.2.15 on 2026-07-25 01:17

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('core', '0008_clinic_agent_enabled_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subjective', models.TextField(blank=True, help_text='S: lo que refiere el paciente.')),
                ('objective', models.TextField(blank=True, help_text='O: hallazgos de la exploración.')),
                ('assessment', models.TextField(blank=True, help_text='A: análisis / juicio clínico.')),
                ('plan', models.TextField(blank=True, help_text='P: plan de actuación.')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada')], db_index=True, default='draft', max_length=10)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, help_text='sha256:<hexdigest> del contenido SOAP y los metadatos de firma.', max_length=100)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
            ],
            options={
                'verbose_name': 'nota clínica',
                'verbose_name_plural': 'notas clínicas',
                'db_table': 'clinical_note',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Contenido de la adenda.')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='clinical.clinicalnote')),
            ],
            options={
                'verbose_name': 'adenda',
                'verbose_name_plural': 'adendas',
                'db_table': 'clinical_addendum',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(help_text='Número de historia, p. ej. HC-2026-00001.', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_histories', to='core.clinic')),
                ('patient', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historia clínica',
                'verbose_name_plural': 'historias clínicas',
                'db_table': 'clinical_medical_history',
                'ordering': ['number'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'unique_together': {('clinic', 'number')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(help_text='Motivo de consulta.')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=10)),
                ('responsible_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='clinical.medicalhistory')),
            ],
            options={
                'verbose_name': 'episodio',
                'verbose_name_plural': 'episodios',
                'db_table': 'clinical_episode',
                'ordering': ['-opened_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='clinical.episode')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appointments.professional')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
                'db_table': 'clinical_visit',
                'ordering': ['-occurred_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='clinical.visit'),
        ),
        migrations.CreateModel(
            name='HistorySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.clinic')),
            ],
            options={
                'verbose_name': 'secuencia de numeración de historias',
                'verbose_name_plural': 'secuencias de numeración de historias',
                'db_table': 'clinical_history_sequence',
                'unique_together': {('clinic', 'year')},
            },
        ),
    ]
