# Generated by Django 5.2.15 on 2026-07-27 21:30

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('clinical', '0002_immutability_triggers'),
        ('core', '0008_clinic_agent_enabled_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, help_text='Especialidad o tipo de cuestionario, p. ej. «podología general».', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Un cuestionario inactivo no se ofrece para rellenar.')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_templates', to='core.clinic')),
            ],
            options={
                'verbose_name': 'cuestionario',
                'verbose_name_plural': 'cuestionarios',
                'db_table': 'clinical_questionnaire_template',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'unique_together': {('clinic', 'name')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField(help_text='Correlativo dentro del cuestionario; se asigna solo.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Versión que se sirve al rellenar. Solo una por cuestionario.')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='clinical.questionnairetemplate')),
            ],
            options={
                'verbose_name': 'versión de cuestionario',
                'verbose_name_plural': 'versiones de cuestionario',
                'db_table': 'clinical_template_version',
                'ordering': ['template', '-number'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('professional', 'Profesional'), ('patient_web', 'Paciente (web)'), ('patient_whatsapp', 'Paciente (WhatsApp)')], db_index=True, default='professional', max_length=20)),
                ('snapshot', models.JSONField(default=list, help_text='Copia literal de las preguntas y las respuestas dadas.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Profesional que lo registró; vacío si lo rellenó el paciente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_responses', to='clinical.episode')),
                ('patient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questionnaire_responses', to='patients.patient')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='clinical.templateversion')),
            ],
            options={
                'verbose_name': 'respuesta de cuestionario',
                'verbose_name_plural': 'respuestas de cuestionario',
                'db_table': 'clinical_questionnaire_response',
                'ordering': ['-filled_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(help_text='Enunciado literal de la pregunta.')),
                ('answer_type', models.CharField(choices=[('boolean', 'Sí / No'), ('text', 'Texto libre'), ('single_choice', 'Opción única'), ('multiple_choice', 'Opción múltiple'), ('number', 'Número')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Lista de opciones; solo para los tipos de elección.')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='clinical.templateversion')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'db_table': 'clinical_question',
                'ordering': ['version', 'order', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('template',), name='clinical_one_current_version_per_template'),
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'number')},
        ),
    ]
