# Generated by Django 5.2.15 on 2026-07-27 22:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('clinical', '0004_questionnaire_immutability_triggers'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alert_type', models.CharField(choices=[('diabetes', 'Diabetes'), ('peripheral_vascular_disease', 'Enfermedad vascular periférica'), ('neuropathy', 'Neuropatía'), ('anticoagulants', 'Tratamiento anticoagulante'), ('allergy_latex', 'Alergia al látex'), ('allergy_local_anesthetics', 'Alergia a anestésicos locales'), ('other', 'Otra')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('warning', 'Advertencia'), ('info', 'Informativa')], db_index=True, default='warning', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('derived', 'Derivada de una anamnesis')], db_index=True, default='manual', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Detalle del aviso.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Profesional que la dio de alta; vacío si la levantó el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('patient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinical_alerts', to='patients.patient')),
                ('source_response', models.ForeignKey(blank=True, help_text='Respuesta de anamnesis de la que se derivó. Vacío si es manual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_alerts', to='clinical.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'alerta clínica',
                'verbose_name_plural': 'alertas clínicas',
                'db_table': 'clinical_alert',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['patient', 'is_active', 'severity'], name='idx_clinical_alert_patient')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
