# Generated by Django 5.2.15 on 2026-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('clinical', '0005_clinical_alerts'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.SlugField(blank=True, help_text='Identificador estable entre versiones, p. ej. «has_diabetes». Es la clave por la que el motor de alertas reconoce la pregunta.', max_length=60, null=True),
        ),
        migrations.AddConstraint(
            model_name='clinicalalert',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('source', 'derived')), fields=('patient', 'alert_type', 'source_response'), name='clinical_unique_derived_alert'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('version', 'code'), name='clinical_unique_question_code_per_version'),
        ),
    ]
