# Generated by Django 5.2.15 on 2026-07-27 23:35

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('clinical', '0006_question_code_and_derived_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('laterality', models.CharField(choices=[('left', 'Pie izquierdo'), ('right', 'Pie derecho')], db_index=True, max_length=5)),
                ('view', models.CharField(choices=[('dorsal', 'Dorsal'), ('plantar', 'Plantar'), ('medial', 'Medial'), ('lateral', 'Lateral')], db_index=True, max_length=10)),
                ('anatomical_zone', models.CharField(choices=[('hallux', 'Hallux (primer dedo)'), ('second_toe', 'Segundo dedo'), ('third_toe', 'Tercer dedo'), ('fourth_toe', 'Cuarto dedo'), ('fifth_toe', 'Quinto dedo'), ('first_metatarsal', 'Primer metatarsiano'), ('second_metatarsal', 'Segundo metatarsiano'), ('third_metatarsal', 'Tercer metatarsiano'), ('fourth_metatarsal', 'Cuarto metatarsiano'), ('fifth_metatarsal', 'Quinto metatarsiano'), ('interdigital', 'Espacio interdigital'), ('midfoot', 'Mediopié'), ('medial_arch', 'Arco medial'), ('lateral_border', 'Borde lateral'), ('heel', 'Talón'), ('ankle', 'Tobillo'), ('other', 'Otra zona')], db_index=True, help_text='Zona clínica. Es el dato que sobrevive a un rediseño del mapa.', max_length=30)),
                ('x', models.FloatField(help_text='Fracción horizontal del SVG (0–1), nunca píxeles.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('y', models.FloatField(help_text='Fracción vertical del SVG (0–1), nunca píxeles.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lesion_type', models.CharField(choices=[('ulcer', 'Úlcera'), ('hyperkeratosis', 'Hiperqueratosis'), ('wound', 'Herida'), ('blister', 'Ampolla'), ('other', 'Otra')], db_index=True, default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('resolved', 'Resuelta')], db_index=True, default='active', max_length=10)),
                ('detected_at', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesions', to='clinical.episode')),
            ],
            options={
                'verbose_name': 'lesión',
                'verbose_name_plural': 'lesiones',
                'db_table': 'clinical_lesion',
                'ordering': ['-detected_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['episode', 'laterality', 'view'], name='idx_lesion_episode_view')],
                'constraints': [models.CheckConstraint(condition=models.Q(('x__gte', 0.0), ('x__lte', 1.0), ('y__gte', 0.0), ('y__lte', 1.0)), name='clinical_lesion_coordinates_normalized'), models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status', 'resolved')), models.Q(('resolved_at__isnull', True), ('status', 'active')), _connector='OR'), name='clinical_lesion_resolved_at_matches_status')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
