# Generated by Django 5.2.15 on 2026-07-28 00:57

#
# Seguimiento de lesiones: la observación (medidas por visita) y sus fotos.
#
# El adjunto guarda la CLAVE del objeto en un bucket privado, jamás una URL: las
# URLs se firman en cada petición y caducan (`clinical/attachments.py`). Y la
# clave la genera `clinical.files.attachment_upload_to`, que la construye con un
# UUID para que no diga nada del paciente ni se pueda adivinar.

import clinical.files
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('clinical', '0007_lesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observed_at', models.DateField(default=django.utils.timezone.localdate, help_text='Día de la observación. Es el eje de la evolución.')),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, help_text='Largo en milímetros.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, help_text='Ancho en milímetros.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=1, help_text='Profundidad en milímetros.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Descripción clínica del estado.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='clinical.lesion')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesion_observations', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'observación de lesión',
                'verbose_name_plural': 'observaciones de lesión',
                'db_table': 'clinical_lesion_observation',
                'ordering': ['-observed_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LesionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(help_text='Clave del objeto en el bucket privado. Nunca una URL.', max_length=255, storage=clinical.files.clinical_media_storage, upload_to=clinical.files.attachment_upload_to)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo real del contenido, deducido al validar. No lo elige quien sube.', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='sha256:<hexdigest> del contenido tal y como se subió.', max_length=71)),
                ('source', models.CharField(choices=[('professional', 'Profesional'), ('patient_whatsapp', 'Paciente (WhatsApp)'), ('patient_web', 'Paciente (web)')], db_index=True, default='professional', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='clinical.lesionobservation')),
            ],
            options={
                'verbose_name': 'adjunto de lesión',
                'verbose_name_plural': 'adjuntos de lesión',
                'db_table': 'clinical_lesion_attachment',
                'ordering': ['-uploaded_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='lesionobservation',
            index=models.Index(fields=['lesion', 'observed_at'], name='idx_lesion_obs_series'),
        ),
        migrations.AddConstraint(
            model_name='lesionobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('length_mm__isnull', True), ('length_mm__gte', 0), _connector='OR'), models.Q(('width_mm__isnull', True), ('width_mm__gte', 0), _connector='OR'), models.Q(('depth_mm__isnull', True), ('depth_mm__gte', 0), _connector='OR')), name='clinical_lesion_observation_measurements_positive'),
        ),
    ]
