# Generated by Django 5.2.15 on 2026-07-28 17:26

#
# Procedimientos realizados: la costura entre la visita y la facturación.
#
# El nombre y el precio del servicio se guardan CONGELADOS (`frozen_service_name`,
# `frozen_price`) en el momento de registrar el procedimiento. La FK al catálogo
# queda como procedencia, sin restricción en base de datos (`db_constraint=False`)
# y con `DO_NOTHING`: retirar un servicio del catálogo no arrastra, no bloquea y
# no dispara un UPDATE masivo sobre procedimientos ya hechos.

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
        ('clinical', '0008_lesion_observations_and_attachments'),
        ('services', '0004_seed_podiatry_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformedProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('frozen_service_name', models.CharField(help_text='Nombre del servicio el día que se hizo. Copia, no referencia.', max_length=255)),
                ('frozen_price', models.DecimalField(decimal_places=2, help_text='Importe del procedimiento el día que se hizo. No se relee del catálogo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('laterality', models.CharField(blank=True, choices=[('left', 'Pie izquierdo'), ('right', 'Pie derecho')], help_text='Pie sobre el que se actuó, si aplica.', max_length=5)),
                ('affected_zone', models.CharField(blank=True, choices=[('hallux', 'Hallux (primer dedo)'), ('second_toe', 'Segundo dedo'), ('third_toe', 'Tercer dedo'), ('fourth_toe', 'Cuarto dedo'), ('fifth_toe', 'Quinto dedo'), ('first_metatarsal', 'Primer metatarsiano'), ('second_metatarsal', 'Segundo metatarsiano'), ('third_metatarsal', 'Tercer metatarsiano'), ('fourth_metatarsal', 'Cuarto metatarsiano'), ('fifth_metatarsal', 'Quinto metatarsiano'), ('interdigital', 'Espacio interdigital'), ('midfoot', 'Mediopié'), ('medial_arch', 'Arco medial'), ('lateral_border', 'Borde lateral'), ('heel', 'Talón'), ('ankle', 'Tobillo'), ('other', 'Otra zona')], db_index=True, help_text='Zona o pieza tratada. Codificada, como en la lesión: nunca texto libre.', max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.professional')),
                ('service', models.ForeignKey(db_constraint=False, help_text='Entrada del catálogo de la que salió. Procedencia, no precio.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='performed_procedures', to='services.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'procedimiento realizado',
                'verbose_name_plural': 'procedimientos realizados',
                'db_table': 'clinical_performed_procedure',
                'ordering': ['-performed_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['visit', 'performed_at'], name='idx_procedure_visit')],
                'constraints': [models.CheckConstraint(condition=models.Q(('frozen_price__gte', 0)), name='clinical_performed_procedure_price_positive')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
