#
# Consentimiento informado: documento lógico → versiones → firmas.
#
# Mismo esquema que la anamnesis y por el mismo motivo: hay que poder responder
# años después a «qué texto tenía delante este paciente cuando firmó». El
# versionado congela el documento al publicarlo; `SignedConsent.text_copy` guarda
# ADEMÁS una copia literal del texto firmado, redundante a propósito, para que la
# prueba no dependa de que la versión siga existiendo intacta.
#
# La firma es una imagen y va al bucket privado (`clinical/files.py`): se guarda
# la clave del objeto, jamás una URL. La inmutabilidad por debajo del ORM la pone
# la migración 0011.

# Generated by Django 5.2.15 on 2026-07-28 17:33

import clinical.files
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_performed_procedure'),
        ('core', '0008_clinic_agent_enabled_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, help_text='Especialidad o tipo de consentimiento, p. ej. «cirugía ungueal».', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Un consentimiento inactivo no se ofrece para firmar.')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_templates', to='core.clinic')),
            ],
            options={
                'verbose_name': 'consentimiento informado',
                'verbose_name_plural': 'consentimientos informados',
                'db_table': 'clinical_consent_template',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'unique_together': {('clinic', 'name')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField(help_text='Correlativo dentro del consentimiento; se asigna solo.')),
                ('text', models.TextField(blank=True, help_text='Texto íntegro del consentimiento, tal y como se firma.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Versión que se ofrece al firmar. Solo una por documento.')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='clinical.consenttemplate')),
            ],
            options={
                'verbose_name': 'versión de consentimiento',
                'verbose_name_plural': 'versiones de consentimiento',
                'db_table': 'clinical_consent_version',
                'ordering': ['template', '-number'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SignedConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text_copy', models.TextField(help_text='Copia literal del texto firmado. No es un duplicado ocioso: es lo que prueba qué aceptó el paciente.')),
                ('signature_image', models.FileField(help_text='Clave del objeto en el bucket privado. Nunca una URL.', max_length=255, storage=clinical.files.clinical_media_storage, upload_to=clinical.files.signature_upload_to)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo real del contenido, deducido al validar. No lo elige quien sube.', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='sha256:<hexdigest> de la firma tal y como se subió.', max_length=71)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_consents', to='clinical.episode')),
                ('patient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_consents', to='patients.patient')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='clinical.consentversion')),
            ],
            options={
                'verbose_name': 'consentimiento firmado',
                'verbose_name_plural': 'consentimientos firmados',
                'db_table': 'clinical_signed_consent',
                'ordering': ['-signed_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='consentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('template',), name='clinical_one_current_consent_per_template'),
        ),
        migrations.AlterUniqueTogether(
            name='consentversion',
            unique_together={('template', 'number')},
        ),
        migrations.AddIndex(
            model_name='signedconsent',
            index=models.Index(fields=['patient', 'signed_at'], name='idx_signed_consent_patient'),
        ),
    ]
