# Generated by Django 5.2.15 on 2026-09-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoicesequence_patientinvoice'),
        ('clinical', '0011_consent_immutability_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedprocedure',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Factura donde se cobró. Null = pendiente de facturar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='billing.patientinvoice'),
        ),
    ]
