# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'suscripción', 'verbose_name_plural': 'suscripciones'},
        ),
    ]
