# Generated by Django 5.2.15 on 2026-09-06 21:18

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscription_options'),
        ('core', '0009_alter_clinic_options_alter_user_options'),
        ('patients', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.clinic')),
            ],
            options={
                'verbose_name': 'serie de facturación',
                'verbose_name_plural': 'series de facturación',
                'db_table': 'billing_invoice_sequence',
                'unique_together': {('clinic', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PatientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('frozen_patient_name', models.CharField(blank=True, help_text='Nombre del paciente al emitir. Copia, no referencia: la factura sigue siendo legible si el paciente se borra.', max_length=301)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('void', 'Anulada')], db_index=True, default='draft', max_length=10)),
                ('number', models.CharField(blank=True, help_text='Número de factura, p. ej. F-2026-00001. Nulo mientras es borrador.', max_length=20, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe cobrado. Se recalcula mientras es borrador y se congela al emitir.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lines', models.JSONField(blank=True, default=list, help_text='Copia literal de las líneas cobradas al emitir. Lo que la factura dice está aquí, no en las FKs.')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Motivo de la anulación.')),
                ('clinic', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_invoices', to='core.clinic')),
                ('patient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='patients.patient')),
            ],
            options={
                'verbose_name': 'factura de paciente',
                'verbose_name_plural': 'facturas de paciente',
                'db_table': 'billing_patient_invoice',
                'ordering': ['-issued_at', '-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_invoice_patient_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='billing_patient_invoice_total_positive'), models.CheckConstraint(condition=models.Q(models.Q(('issued_at__isnull', True), ('number__isnull', True), ('status', 'draft')), models.Q(('issued_at__isnull', False), ('number__isnull', False), ('status__in', ['issued', 'void'])), _connector='OR'), name='billing_patient_invoice_number_only_when_issued')],
                'unique_together': {('clinic', 'number')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
