# Generated by Django 5.2.15 on 2026-09-07 00:31

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_appointment_options_and_more'),
        ('billing', '0003_invoicesequence_patientinvoice'),
        ('core', '0009_alter_clinic_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Profesional que registró la factura. Vacío si no lo hubo.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.professional'),
        ),
        migrations.AddField(
            model_name='patientinvoice',
            name='frozen_created_by_name',
            field=models.CharField(blank=True, help_text='Nombre de quien la registró, al emitir. Copia, no referencia.', max_length=255),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('frozen_patient_name', models.CharField(blank=True, help_text='Nombre del paciente al cobrar. Copia, no referencia.', max_length=301)),
                ('frozen_invoice_number', models.CharField(blank=True, help_text='Número de la factura cobrada. Copia: el recibo se lee solo.', max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Número de recibo, p. ej. R-2026-00001. Se asigna al registrarlo.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe cobrado. Un recibo de cero euros no prueba nada.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('bizum', 'Bizum'), ('cash', 'Efectivo')], db_index=True, max_length=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo entró el dinero.')),
                ('frozen_created_by_name', models.CharField(blank=True, help_text='Nombre de quien cobró, al registrar. Copia, no referencia.', max_length=255)),
                ('clinic', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Profesional que registró el cobro. Vacío si no lo hubo.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.professional')),
                ('invoice', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='billing.patientinvoice')),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
                'db_table': 'billing_payment',
                'ordering': ['-paid_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['invoice', 'paid_at'], name='idx_payment_invoice_paid')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_payment_amount_positive')],
                'unique_together': {('clinic', 'receipt_number')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.clinic')),
            ],
            options={
                'verbose_name': 'serie de recibos',
                'verbose_name_plural': 'series de recibos',
                'db_table': 'billing_receipt_sequence',
                'unique_together': {('clinic', 'year')},
            },
        ),
    ]
