# Generated by Django 5.2.15 on 2026-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_appointment_options_and_more'),
        ('billing', '0004_payment'),
        ('core', '0009_alter_clinic_options_alter_user_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['clinic', 'paid_at'], name='idx_payment_clinic_paid'),
        ),
    ]
