# Generated by Django 5.2.13 on 2026-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicknowledgebase",
            name="kb_type",
            field=models.CharField(
                choices=[
                    ("services", "Servicios"),
                    ("pricing", "Precios"),
                    ("schedule", "Horarios"),
                    ("faq", "FAQ"),
                    ("location", "Ubicación"),
                    ("policies", "Políticas"),
                    ("team", "Equipo"),
                ],
                max_length=50,
            ),
        ),
    ]
