# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_clinicknowledgebase_kb_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicinfocache',
            options={'verbose_name': 'respuesta en caché', 'verbose_name_plural': 'respuestas en caché'},
        ),
        migrations.AlterModelOptions(
            name='clinicinfoquery',
            options={'verbose_name': 'consulta de información', 'verbose_name_plural': 'consultas de información'},
        ),
        migrations.AlterModelOptions(
            name='clinicknowledgebase',
            options={'verbose_name': 'entrada de la base de conocimiento', 'verbose_name_plural': 'entradas de la base de conocimiento'},
        ),
    ]
