# Generated by Django 5.2.12 on 2026-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=models.CharField(default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='nif',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
