# Generated by Django 5.2.12 on 2026-04-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_clinic_address_and_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, upload_to='clinic_logos/'),
        ),
    ]
