# Generated by Django 5.2.12 on 2026-05-04 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_logo_to_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='agent_api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='API Key única que usa n8n para autenticarse con esta clínica', unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='whatsapp_token',
            field=models.CharField(blank=True, default='', help_text='Token de acceso permanente de la WhatsApp Cloud API', max_length=500),
        ),
        migrations.AddField(
            model_name='clinic',
            name='whatsapp_verify_token',
            field=models.CharField(blank=True, default='', help_text='Token de verificación del webhook de Meta', max_length=100),
        ),
    ]
