# Generated by Django 5.2.12 on 2026-07-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clinic_agent_api_key_clinic_whatsapp_token_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='test_patient',
            field=models.ForeignKey(blank=True, help_text='Paciente de prueba para testear el agente desde el panel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient'),
        ),
    ]
