# Generated by Django 5.2.12 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clinic_test_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='hold_ttl_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='Minutos que una cita creada por el agente o la reserva pública queda reservada esperando validación del staff. Pasado ese plazo se cancela y el hueco se libera. 0 = sin caducidad.'),
        ),
    ]
