# Generated by Django 5.2.16 on 2026-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clinic_hold_ttl_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='agent_enabled',
            field=models.BooleanField(default=True, help_text='Interruptor general del agente. Si se apaga, el agente deja de responder en todos los chats de la clínica y la atención pasa a ser manual.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='agent_handoff_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Segundos de inactividad del staff tras los que el agente retoma automáticamente una conversación puesta en modo humano.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='conversation_retention_months',
            field=models.PositiveIntegerField(default=24, help_text='Meses que se conserva el histórico de conversaciones antes de purgarse. 0 = sin límite.'),
        ),
    ]
