# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clinic_agent_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'clínica', 'verbose_name_plural': 'clínicas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
