# Generated by Django 5.2.15 on 2026-10-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_clinic_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='min_booking_notice_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Antelación mínima, en minutos, para reservar por la vía online (agente y API): no se ofrecen ni se aceptan citas que empiecen antes de ahora + este plazo. El staff desde el panel no está sujeto. 0 = sin mínimo.'),
        ),
    ]
