# Generated by Django 5.2.15 on 2026-07-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_max_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_type',
            field=models.CharField(choices=[('fixed', 'Fijo'), ('variable', 'Variable')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fijo'), ('variable', 'Variable')], default='fixed', max_length=10),
        ),
    ]
