# Generated by Django 5.2.15 on 2026-07-24 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_repr', models.CharField(blank=True, help_text='Identidad del actor en el momento del evento. Para el agente de n8n vale «n8n:<clinic_id>» y el FK queda a nulo, porque el agente no es un usuario del sistema.', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('origin', models.CharField(choices=[('web', 'Panel web'), ('api', 'API'), ('admin', 'Admin de Django'), ('command', 'Comando / tarea'), ('n8n', 'Agente n8n')], db_index=True, default='command', max_length=20)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('view', 'Ver ficha'), ('list', 'Listar'), ('search', 'Buscar'), ('export', 'Exportar'), ('print', 'Imprimir'), ('download_attachment', 'Descargar adjunto')], db_index=True, max_length=25)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('result_count', models.PositiveIntegerField(blank=True, help_text='Número de registros devueltos en listados y búsquedas.', null=True)),
                ('reason', models.TextField(blank=True, help_text='Justificación del acceso. Reservado para accesos excepcionales que en el futuro requieran motivar la consulta.', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, help_text='Paciente afectado, cuando el evento se puede atribuir a uno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de acceso',
                'verbose_name_plural': 'registros de accesos',
                'db_table': 'audit_access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='idx_accesslog_patient'), models.Index(fields=['user', '-timestamp'], name='idx_accesslog_user'), models.Index(fields=['content_type', 'object_id'], name='idx_accesslog_object')],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_repr', models.CharField(blank=True, help_text='Identidad del actor en el momento del evento. Para el agente de n8n vale «n8n:<clinic_id>» y el FK queda a nulo, porque el agente no es un usuario del sistema.', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('origin', models.CharField(choices=[('web', 'Panel web'), ('api', 'API'), ('admin', 'Admin de Django'), ('command', 'Comando / tarea'), ('n8n', 'Agente n8n')], db_index=True, default='command', max_length=20)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('model_label', models.CharField(blank=True, db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('create', 'Alta'), ('update', 'Modificación'), ('delete', 'Baja')], db_index=True, max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Diff con la forma {campo: {"before": ..., "after": ...}}. Los campos marcados como sensibles al registrar el modelo aparecen como {campo: {"changed": true}}, sin valores: este log no puede ser una segunda copia sin cifrar de la historia clínica.')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, help_text='Paciente afectado, cuando el evento se puede atribuir a uno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de cambio',
                'verbose_name_plural': 'registros de cambios',
                'db_table': 'audit_change_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='idx_changelog_patient'), models.Index(fields=['user', '-timestamp'], name='idx_changelog_user'), models.Index(fields=['content_type', 'object_id'], name='idx_changelog_object')],
            },
        ),
    ]
