# Generated by Django 5.2.12 on 2026-07-24 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_immutability_triggers'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Paciente afectado, cuando el evento se puede atribuir a uno.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Paciente afectado, cuando el evento se puede atribuir a uno.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
