# Generated by Django 5.2.15 on 2026-08-07 02:46
#
# Nueva acción `password_change`. Cambian los `choices` y nada más: el tipo y el
# `max_length` son los de siempre, así que la migración no emite SQL sobre la
# tabla y no roza el trigger de inmutabilidad de `0002`.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_accesslog_content_type_alter_accesslog_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'Ver ficha'), ('list', 'Listar'), ('search', 'Buscar'), ('export', 'Exportar'), ('print', 'Imprimir'), ('download_attachment', 'Descargar adjunto'), ('password_change', 'Cambio de contraseña')], db_index=True, max_length=25),
        ),
    ]
