# Generated by Django 5.2.12 on 2026-03-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_clinic__a92c88_idx',
            old_name='appointmen_clinic__fe1c70_idx',
        ),
    ]
