# Generated by Django 5.2.13 on 2026-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmada"),
                    ("cancelled", "Cancelada"),
                    ("rescheduled", "Reagendada"),
                    ("no_show", "No asistió"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
