# Generated by Django 5.2.12 on 2026-03-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_clinic_scheduled_at_status',
            old_name='idx_appointments_clinic_dt_status',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_phone_status_scheduled_at',
            old_name='idx_appointments_phone_status_dt',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_appointments_remdr_flags',
            old_name='idx_appointments_reminder_flags',
        ),
    ]
