# Generated by Django 5.2.13 on 2026-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_backfill_professionals_from_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="professional_type",
            field=models.CharField(
                choices=[
                    ("medico", "Médico"),
                    ("dentista", "Dentista"),
                    ("psicologo", "Psicólogo"),
                    ("enfermero", "Enfermero/a"),
                    ("fisioterapeuta", "Fisioterapeuta"),
                    ("nutricionista", "Nutricionista"),
                ],
                default="medico",
                max_length=30,
            ),
        ),
    ]
