# Generated by Django 5.2.12 on 2026-04-15 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_professional_professional_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.professional')),
            ],
            options={
                'db_table': 'professional_schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('professional', 'day_of_week')},
            },
        ),
    ]
