# Generated by Django 5.2.12 on 2026-04-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_professional_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Paciente'), ('staff', 'Clínica')], max_length=10, null=True),
        ),
    ]
