# Generated by Django 5.2.12 on 2026-04-29 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_add_cancelled_by_to_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'No asistió')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'No asistió')], max_length=20)),
                ('actor', models.CharField(choices=[('patient', 'Paciente'), ('staff', 'Clínica'), ('system', 'Sistema')], default='system', max_length=10)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_status_history',
                'ordering': ['changed_at'],
            },
        ),
    ]
