# Generated by Django 5.2.12 on 2026-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_add_appointment_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, upload_to='professional_photos/'),
        ),
    ]
