# Generated by Django 5.2.12 on 2026-06-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_professional_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'No asistió')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'No asistió')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentstatushistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'No asistió')], max_length=20),
        ),
    ]
