# Generated by Django 5.2.15 on 2026-07-13 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacaciones'), ('sick_leave', 'Baja'), ('training', 'Formación'), ('other', 'Otro')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'professional_time_off',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='professionalschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='professional',
            name='accepts_online_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='buffer_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='slot_granularity_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='professional',
            name='professional_type',
            field=models.CharField(choices=[('medico', 'Médico'), ('dentista', 'Dentista'), ('psicologo', 'Psicólogo'), ('enfermero', 'Enfermero/a'), ('fisioterapeuta', 'Fisioterapeuta'), ('nutricionista', 'Nutricionista'), ('podologo', 'Podólogo')], default='medico', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='professionalschedule',
            constraint=models.UniqueConstraint(fields=('professional', 'day_of_week', 'start_time'), name='uniq_prof_day_start'),
        ),
        migrations.AddField(
            model_name='professionaltimeoff',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='appointments.professional'),
        ),
        migrations.AddIndex(
            model_name='professionaltimeoff',
            index=models.Index(fields=['professional', 'starts_at', 'ends_at'], name='professiona_profess_a6e83e_idx'),
        ),
    ]
