# Generated by Django 5.2.15 on 2026-07-13 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_professionaltimeoff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.professional'),
        ),
    ]
