# Generated by Django 5.2.12 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_appointment_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('agent', 'Agente WhatsApp'), ('staff', 'Panel'), ('booking', 'Reserva pública')], db_index=True, default='staff', max_length=20),
        ),
    ]
