# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_backfill_source_and_patient_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_at'], 'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.AlterModelOptions(
            name='appointmentstatushistory',
            options={'ordering': ['changed_at'], 'verbose_name': 'cambio de estado de cita', 'verbose_name_plural': 'cambios de estado de citas'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['user__first_name', 'user__last_name', 'user__email'], 'verbose_name': 'profesional', 'verbose_name_plural': 'profesionales'},
        ),
        migrations.AlterModelOptions(
            name='professionalschedule',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'horario de profesional', 'verbose_name_plural': 'horarios de profesionales'},
        ),
        migrations.AlterModelOptions(
            name='professionaltimeoff',
            options={'ordering': ['starts_at'], 'verbose_name': 'ausencia de profesional', 'verbose_name_plural': 'ausencias de profesionales'},
        ),
    ]
