# Generated by Django 5.2.15 on 2026-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professional',
            name='license_body',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='professional',
            name='license_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='professional',
            name='title',
            field=models.CharField(blank=True, choices=[('dr', 'Dr.'), ('dra', 'Dra.'), ('d', 'D.'), ('dna', 'Dña.')], max_length=5),
        ),
    ]
