# Generated by Django 5.2.15 on 2026-09-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_professional_title_bio_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatushistory',
            name='actor',
            field=models.CharField(choices=[('patient', 'Paciente'), ('staff', 'Clínica'), ('agent', 'Agente WhatsApp'), ('system', 'Sistema')], default='system', max_length=10),
        ),
    ]
