# Generated by Django 5.2.15 on 2026-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_alter_appointmentstatushistory_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
