# Generated by Django 5.2.15 on 2026-10-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_appointment_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_for_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_relationship',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
