# Generated by Django 5.2.12 on 2026-03-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowerror',
            new_name='idx_workflow_errors',
            old_name='idx_workflow_errors_workflow_dt',
        ),
    ]
