# Generated by Django 5.2.12 on 2026-07-21 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_idx_workflow_errors_workflow_dt_idx_workflow_errors'),
        ('core', '0007_clinic_hold_ttl_minutes'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=10)),
                ('sender', models.CharField(choices=[('patient', 'Paciente'), ('agent', 'Agente'), ('staff', 'Personal')], max_length=10)),
                ('body', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Ubicación'), ('template', 'Plantilla'), ('other', 'Otro')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True)),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('wa_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Marca de tiempo original de WhatsApp.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='clinic',
            field=models.ForeignKey(blank=True, db_column='clinic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinic'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='agent_paused',
            field=models.BooleanField(default=False, help_text='Cuando un humano toma el hilo, el agente deja de responder para que no contesten los dos a la vez.'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='last_message_preview',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Paciente vinculado, si el número coincide con una ficha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['clinic', '-last_message_at'], name='idx_conv_clinic_last_msg'),
        ),
        migrations.AddConstraint(
            model_name='conversationsession',
            constraint=models.UniqueConstraint(fields=('clinic', 'phone'), name='uniq_conversation_clinic_phone'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='clinic',
            field=models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversationsession'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='idx_chat_msg_session'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['clinic', '-created_at'], name='idx_chat_msg_clinic'),
        ),
    ]
