# Generated by Django 5.2.12 on 2026-07-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_chatmessage_agentmemory_clinic_and_more'),
        ('core', '0007_clinic_hold_ttl_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowerror',
            name='clinic',
            field=models.ForeignKey(blank=True, db_column='clinic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinic'),
        ),
    ]
