# Generated by Django 5.2.16 on 2026-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_chatmessage_agentmemory_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='last_staff_message_at',
            field=models.DateTimeField(blank=True, help_text='Último mensaje escrito por una persona del staff. Abre una pausa temporal del agente que se cierra sola por inactividad.', null=True),
        ),
    ]
