# Generated by Django 5.2.12 on 2026-07-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_conversationsession_last_staff_message_at'),
        ('agent', '0004_workflowerror_clinic'),
    ]

    operations = [
    ]
