# Generated by Django 5.2.15 on 2026-07-21 23:38

from django.db import migrations, models


def mark_existing_test_sessions(apps, schema_editor):
    """Marca los hilos de prueba que ya existen antes de que hubiera flag.

    Se reconocen por el teléfono: el del paciente de prueba de la clínica, o el
    literal 'panel-test' que usa la vista cuando no hay ninguno configurado.
    """
    ConversationSession = apps.get_model('agent', 'ConversationSession')
    Clinic = apps.get_model('core', 'Clinic')

    ConversationSession.objects.filter(phone='panel-test').update(is_test=True)

    clinics = Clinic.objects.exclude(test_patient=None).select_related('test_patient')
    for clinic in clinics:
        phone = (clinic.test_patient.phone or '').strip()
        if phone:
            ConversationSession.objects.filter(clinic=clinic, phone=phone).update(is_test=True)


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_merge_20260721_2136'),
        ('core', '0006_clinic_test_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Conversación del banco de pruebas del panel, no de un paciente real. Se guarda igual, pero queda fuera de la bandeja de chats.'),
        ),
        migrations.RunPython(mark_existing_test_sessions, migrations.RunPython.noop),
    ]
