# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_conversationsession_is_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmemory',
            options={'verbose_name': 'memoria del agente', 'verbose_name_plural': 'memorias del agente'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'mensaje de chat', 'verbose_name_plural': 'mensajes de chat'},
        ),
        migrations.AlterModelOptions(
            name='conversationsession',
            options={'verbose_name': 'sesión de conversación', 'verbose_name_plural': 'sesiones de conversación'},
        ),
        migrations.AlterModelOptions(
            name='workflowerror',
            options={'verbose_name': 'error de workflow', 'verbose_name_plural': 'errores de workflow'},
        ),
    ]
