# Generated by Django 5.2.15 on 2026-09-24 17:51

import agent.files
import clinical.files
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_alter_agentmemory_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(help_text='Clave del objeto en el bucket privado. Nunca una URL.', max_length=255, storage=clinical.files.clinical_media_storage, upload_to=agent.files.chat_media_upload_to)),
                ('mime_type', models.CharField(help_text='Tipo real del contenido, deducido al validar.', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(help_text='sha256:<hexdigest> del fichero guardado.', max_length=71)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='agent.chatmessage')),
            ],
            options={
                'verbose_name': 'adjunto de chat',
                'verbose_name_plural': 'adjuntos de chat',
                'db_table': 'chat_attachments',
            },
        ),
    ]
