# Generated by Django 5.2.15 on 2026-09-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_chat_attachment_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo llegó al móvil del paciente (✓✓).', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='seen_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo lo leyó el paciente (✓✓ azul).', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo lo leyó la clínica en el panel (entrantes).', null=True),
        ),
    ]
