# Generated by Django 5.2.15 on 2026-09-28 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_chat_message_delivery'),
        ('core', '0009_alter_clinic_options_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, help_text='Cómo se presenta ante los pacientes. Vacío: sin nombre propio.', max_length=60, verbose_name='nombre del agente')),
                ('tone', models.CharField(choices=[('cercano', 'Cercano'), ('profesional', 'Profesional'), ('formal', 'Formal')], default='profesional', max_length=20, verbose_name='tono')),
                ('address_form', models.CharField(choices=[('tu', 'De tú'), ('usted', 'De usted')], default='tu', max_length=10, verbose_name='trato')),
                ('emoji_usage', models.CharField(choices=[('ninguno', 'Sin emojis'), ('moderado', 'Con moderación')], default='ninguno', max_length=10, verbose_name='emojis')),
                ('welcome_message', models.TextField(blank=True, help_text='Lo que el agente cuenta en su primer mensaje a alguien que no es paciente todavía. Lo adapta a lo que le pregunten, no lo copia literal.', max_length=500, verbose_name='presentación para contactos nuevos')),
                ('style_notes', models.TextField(blank=True, help_text='Expresiones que usar o evitar, cómo despedirse… Solo estilo: no cambia lo que el agente puede hacer.', max_length=800, verbose_name='indicaciones de estilo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='core.clinic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil del agente',
                'verbose_name_plural': 'perfiles del agente',
                'db_table': 'agent_profile',
            },
        ),
    ]
