# Generated by Django 5.2.15 on 2026-10-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_agent_profile'),
        ('patients', '0005_guardian_patientguardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='guardian',
            field=models.ForeignKey(blank=True, help_text='Contacto responsable, si el número es el de uno y no hay ficha con ese teléfono.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='patients.guardian'),
        ),
    ]
