# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
    ]
