# Generated by Django 5.2.15 on 2026-09-30 17:53

import clinical.files
import patients.photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(blank=True, max_length=255, storage=clinical.files.clinical_media_storage, upload_to=patients.photos.patient_photo_upload_to),
        ),
    ]
