# Generated by Django 5.2.15 on 2026-10-09 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clinic_min_booking_notice'),
        ('patients', '0004_patient_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'contacto responsable',
                'verbose_name_plural': 'contactos responsables',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('child', 'Hijo/a'), ('spouse', 'Cónyuge o pareja'), ('parent', 'Padre/madre'), ('sibling', 'Hermano/a'), ('caregiver', 'Cuidador/a'), ('other', 'Otro')], default='other', max_length=20)),
            ],
            options={
                'verbose_name': 'vínculo paciente-contacto',
                'verbose_name_plural': 'vínculos paciente-contacto',
            },
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('clinic', 'email', 'phone'), name='patient_unique_clinic_email_phone'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='patient',
            field=models.OneToOneField(blank=True, help_text='Su propia ficha, si también es paciente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientguardian',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='patients.guardian'),
        ),
        migrations.AddField(
            model_name='patientguardian',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='dependents',
            field=models.ManyToManyField(related_name='guardians', through='patients.PatientGuardian', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='patientguardian',
            constraint=models.UniqueConstraint(fields=('patient', 'guardian'), name='patientguardian_unique'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(fields=('clinic', 'phone'), name='guardian_unique_clinic_phone'),
        ),
    ]
