# Generated by Django 5.2.15 on 2026-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clinic_min_booking_notice'),
        ('patients', '0005_guardian_patientguardian_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guardian',
            name='guardian_unique_clinic_phone',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('clinic', 'phone'), name='guardian_unique_clinic_phone'),
        ),
    ]
