# Generated by Django 5.2.15 on 2026-10-10 19:06

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_guardian_phone_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientguardian',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'verbose_name': 'vínculo paciente-contacto', 'verbose_name_plural': 'vínculos paciente-contacto'},
        ),
        migrations.AlterModelManagers(
            name='patientguardian',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='patientguardian',
            name='patientguardian_unique',
        ),
        migrations.AddField(
            model_name='patientguardian',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='patientguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('patient', 'guardian'), name='patientguardian_unique'),
        ),
    ]
