# Generated by Django 5.2.15 on 2026-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['scheduled_for'], 'verbose_name': 'recordatorio', 'verbose_name_plural': 'recordatorios'},
        ),
    ]
